# fly.toml app configuration file generated for socketio-wordgame on 2024-01-18T17:51:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "socketio-wordgame"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
